export default interface Car{
      id: string,
      brand_id: string,
      model: string,
      year: string,
      color: string,
      img:string,
      price:number,
      license_plate:string,
      mileage:string,
      lat: string,
      lng: string,
      is_premiun:string,
      rental_count: string,
      daily_rate: string,
      status: string,
      created_at: string,
      updated_at: string,
      brand: any
}